### ISSUE TITLE
Allow setting SeachBox label

### ISSUE THREAD

**Issue by romcode** [VelinGeorgiev/spfx-react-search-box-webpart#1]
Hi, 

Would you mind to improve your component allowing to set the text/label inside the searchbox (html placeholder attribute)?

For this, is necessary to change the file /webparts/reactSearchBox/components/ReactSearchBox.tsx

Adding a line for the labelText attribute.

For example: using the same SearchLabel attribute for the button. Or a new one, if you prefer.

            <SearchBox
              className="react-search-box"
              onChange={this._handleInputChange.bind(this)}
              onSearch={this._handleSearch.bind(this)}
              labelText={this.props.strings.SearchLabel} >
            </SearchBox>

thankyou for your work!

Regards.

**Comment by NPrice99** [comment]
You can do this - its part of office-ui-fabric-react :

  public ResultsPageUri: string;

  constructor(props: IReactSearchBoxProps) {
    super(props);

    this.state = {
      searchQuery: "Enter your keyword(s) here"
    } as IReactSearchBoxState;
  }

Regards

Nigel

**Comment by VelinGeorgiev** [comment]
@romcode will try to add the ability to set the text for the label within the next few days.

**Comment by romcode** [comment]
Thanks!

**Comment by VelinGeorgiev** [comment]
Updated. Now there is a property that can overwrite the label of the search button. Will close that one.

**Comment by NPrice99** [comment]
Thanks !
